### ISSUE TITLE
Getting error since evening

### ISSUE THREAD

**Issue by gopalasubramanium** [lavolp3/MMM-AVStock#1]
0|MagicMirror  | { Error: spawn ENOMEM
0|MagicMirror  |     at _errnoException (util.js:1024:11)
0|MagicMirror  |     at ChildProcess.spawn (internal/child_process.js:323:11)
0|MagicMirror  |     at Object.exports.spawn (child_process.js:514:9)
0|MagicMirror  |     at Git._schedule (/home/pi/MagicMirror/node_modules/simple-git/src/git.js:1338:41)
0|MagicMirror  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|MagicMirror  |     at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }
0|MagicMirror  | { Error: spawn ENOMEM
0|MagicMirror  |     at _errnoException (util.js:1024:11)
0|MagicMirror  |     at ChildProcess.spawn (internal/child_process.js:323:11)
0|MagicMirror  |     at Object.exports.spawn (child_process.js:514:9)
0|MagicMirror  |     at Git._schedule (/home/pi/MagicMirror/node_modules/simple-git/src/git.js:1338:41)
0|MagicMirror  |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
0|MagicMirror  |     at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }
0|MagicMirror  | (node:869) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 82): Error: Call to device timed out

**Comment by eouia** [comment]
I’m not sure this error is mine. Especially ‘simple-git’ or ‘spawn’ is not used by this module directly.

**Comment by eouia** [comment]
Not any more information? I'll close this issue. You can ask again whenever you want.
Good luck to you.
