### ISSUE TITLE
Table is left justified instead of right

### ISSUE THREAD

**Issue by leekis** [lavolp3/MMM-AVStock#10]
Table is left justified instead of right. Looked through MMM-AVStock.js but clueless on how to make it left justified. Maybe it's an entry on config.js. Any help would be appreciated.
Thanks!
Ki

**Comment by eouia** [comment]
sorry for late answer. I'm on vacations. 
The look of module could be controlled by CSS. See the `MMM-AVStock.css` then redefine or override  the fields you need on `css/custom.css`.

**Comment by leekis** [comment]
That worked! Updated MMM-AVStock.css with bunch of 'text-align:right;' for the fields I wanted to justify right. Thx!
