### ISSUE TITLE
Alphavantage update interval ?

### ISSUE THREAD

**Issue by tmdag** [lavolp3/MMM-AVStock#12]
While we should be getting 5 requests per minute I am getting like 5 per day instead (last updated shows few hours ago). Is that normal ?

**Comment by lavolp3** [comment]
Are you getting messages from the module via npm start dev? You should receive a console log like "Error: API Call limit exceeded."

**Comment by eouia** [comment]
Sorry for late reply. Could you show me your configuration about MMM-AVStock?
