### ISSUE TITLE
Is there a way to change to updated time to 12 hour format

### ISSUE THREAD

**Issue by Djninja926** [lavolp3/MMM-AVStock#15]
Is there a way to change to the updated time to 12-hour format because it doesn't work well with the other things in my smart mirror config.

**Comment by eouia** [comment]
Well you can modify `timeFormat: ""` to whatever as your wish. 
Current default is `"DD-MM HH:mm"`, so, it will show time like `01-21 23:45`. If you set it as `"Mo DDD, hh:mm a"`, it will show like `21st Jan, 11:45 am`.  Ref. https://momentjs.com/docs/#/displaying/format/

**Comment by Djninja926** [comment]
thanks this method worked
