### ISSUE TITLE
Some Symbols will not load data

### ISSUE THREAD

**Issue by requiemmg** [lavolp3/MMM-AVStock#16]
Hi,

some symbols (e.g. 6AQQ.FRK) will not be displayed in MM2 though the API Call provides data.

e.g.
https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=6aqq.dex&interval=5min&apikey=xxxx

(replace xxx with your api key)

Others work fine.

**Comment by lavolp3** [comment]
I think that is not because of the ticket but because this module currently only supports daily tickers. I have been working on supporting intraday tickers as well but have also meanwhile switched to a pure chart module. Will have a look at my  local process in this module and try to send a pr so intraday tickers can be used

**Comment by eouia** [comment]
Hmmm.. someday I'll rebuild this module to support more features universally. Since I released this module firstly, there be some changes on APIs, But I have missed them.

**Comment by requiemmg** [comment]
Would love to see an update 👍

**Comment by lavolp3** [comment]
tackling this in the coming days by adding the option to show hourly data

**Comment by ajfromaz** [comment]
Relatively new to MM, installed it last November and has been working great, thank you!

For past month or so - the ticker data is from last trading session, ie, a day old. I haven't changed anything in config files. Just did git pull to ensure on latest commit, but no dice. 

Just ran browser query with alphavantage key, and that is also a day old! Do I need to do something in alphavantage account?

https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=goog&apikey=xxxxxx

**Comment by lavolp3** [comment]
One forum user has the same issue. I can't confirm that for the time series call.
Since I'm working on a new version with different API calls, the global quote will not be called anymore in future, so this might be a workaround.
However, I canÄt really comprehend the issue. Need to take a closer look.

**Comment by elgeorgie** [comment]
I have been using the same config and tracking the same stock/indices and with the latest update, nothing is being displayed for the SP&500, DOW and other indices.  Anyone else having the same issue or have a workaround?  Thanks!

**Comment by elirosen** [comment]
> I have been using the same config and tracking the same stock/indices and with the latest update, nothing is being displayed for the SP&500, DOW and other indices. Anyone else having the same issue or have a workaround? Thanks!

I am having the same issue with indices. Came here to see if it was a known issue or if I messed something up in the config.

**Comment by lavolp3** [comment]
Give me the weekend to look after it.
@elirosen Can you please post your config?

**Comment by ajfromaz** [comment]
@lavolp3 thanks for your time!
Please note all of the issues seem to be with alphavantage (test with browser query first) rather than MM module.
1. Nasdaq stocks seem to be updated only at close of trading.
2. Some indices not working anymore.

**Comment by lavolp3** [comment]
During some extensive work on an update I recognized that more and more often (currently every day) I seem to only get past days values. and never the current day's not to mention more recent ones.
Does anyone have an idea for a better API provide?

**Comment by ajfromaz** [comment]
IEX Cloud? As used by another stocks module - https://github.com/Elaniobro/MMM-stocks

**Comment by lavolp3** [comment]
> IEX Cloud? As used by another stocks module - https://github.com/Elaniobro/MMM-stocks

Looks good, thanks! Will try it out!

**Comment by requiemmg** [comment]
I know you are working on a new API - great.
Could it be AlphaVantage 
- is sorting out non-US markets? I can hardly find values from MDAX or TecDax in EUR currency (which is a pain in the ... for the great PurchasePrice feature) (Try to search for "Alstria" e.g., it will only show "ALSRF" symbol, the old "AOX.DEX" for the Xetra value is not shown anymore in the search results)
- only shows closing values from a day ago for a while for free users?

Hope that a new API will be better 👍

**Comment by lavolp3** [comment]
Both is true. Especially the latest one is a real pain. I'm working on using IE as source.
But I'm afraid that won't cover german stocks much better. DAX stocks may be included. MDAX or TecDax will be difficult.
I'm from Germany as well but only using US stocks and EURUSD here.

**Comment by requiemmg** [comment]
Hope there will be a solution

**Comment by humdinger44** [comment]
I've noticed my BTC-USD charts no longer loads as well. No doubt this is due to changes on alphavantage's side, but if anyone knows a work around please let me know. Its an exciting time to be watching BTC.
