### ISSUE TITLE
HOW TO : Follow the CAC40 stock market index

### ISSUE THREAD

**Issue by thymon13** [lavolp3/MMM-AVStock#17]
Hello,

My question is in the title :)
I can't follow the : PX1 symbol

**Comment by popeye2002** [comment]
`	{
	module: "MMM-Jast",
	position: "bottom_bar",
	config: {
		updateIntervalInSeconds: 3600,
		fadeSpeedInSeconds: 3.5,	
			stocks: [
			{ name: "Amazon", symbol: "AMZN" },
			{ name: "CAC40", symbol: "^FCHI"},`

**Comment by popeye2002** [comment]
here is the config.js you need

 {
 module: "MMM-Jast",
 position: "bottom_bar",
 config: {
 updateIntervalInSeconds: 3600,
 fadeSpeedInSeconds: 3.5, 
 stocks: [
 { name: "Amazon", symbol: "AMZN" },
 { name: "CAC40", symbol: "^FCHI"},

Scott Brown 
"Life is Good"

     On Sunday, May 3, 2020, 04:27:39 PM PDT, Thymon <notifications@github.com> wrote:  
 
 


Hello,

My question is in the title :)
I can't follow the : PX1 symbol

**Comment by thymon13** [comment]
> symbol: "^FCHI"

Damn ! That's it ! Thanks a lot !
