### ISSUE TITLE
No data loading

### ISSUE THREAD

**Issue by requiemmg** [lavolp3/MMM-AVStock#19]
Did anything change? I paused to use this module, just commented out my configuration.
Now activated it back again, the module itself loads, but it does not load any data.
I can query alphavantage in my browser ok with my API key.
I updated to the current build. Anyone else experiencing problems?

**Comment by lavolp3** [comment]
The module has been moved to my account, but that should not change anything.
Try removing it and installing it again using `git clone https://github.com/lavolp3/MMM-AVStock` and `npm install`

**Comment by lavolp3** [comment]
and please post your config here.

**Comment by requiemmg** [comment]
Deleted, re-cloned an npm installed from this repo, no difference. This is my config file. Tried with only one value (AAPL), no difference.

		{
			module: "MMM-AVStock",
			disabled: 'false',
			position: "bottom_center", //"bottom_bar" is better for `mode:ticker`
			config: {
				apiKey : "deleted my API key here", // https://www.alphavantage.co/
				timeFormat: "DD-MM-YYYY HH:mm:ss",
				symbols : ["18MP.DEX", "IBCD.FRK", "PR1C.FRK", "IUSM.FRK", "EUNH.FRK", "XUEM.FRK", "IQQ7.FRK", "D5BK.FRK", "SXR1.FRK", "QDVI.FRK", "QDVA.FRK", "IS3N.FRK", "CEMR.FRK", "CEMS.FRK", "DX2J.FRK", "XDJP.FRK", "6AQQ.FRK"],
				alias: ["Amundi ETF MSCI World ETF", "iShares $ Corporate Bond ETF", "Amundi Prime Euro Corporates ETF", "iShares USD Treasury Bond", "iShares Core Euro Government Bond", "Xtrackers USD Emerging Markets Bond", "iShares US Property Yield", "Xtrackers FTSE Developed Europe Real Estate", "iShares Core MSCI Pacific ex-Japan", "iShares Edge MSCI USA Value Factor", "iShares Edge MSCI USA Momentum Factor", "iShares Core MSCI Emerging Markets", "iShares Edge MSCI Europe Momentum Factor", "iShares Edge MSCI Europe Value Factor", "Xtrackers MSCI Europe Small Cap", "Xtrackers Nikkei 225 UCITS ETF", "Amundi ETF NASDAQ 100 UCITS ETF"], 
				tickerDuration: 45, // Ticker will be cycled once per this second.
				chartDays: 50, //For `mode:series`, how much daily data will be taken. (max. 90)
				poolInterval : 1000*15, // (Changed in ver 1.1.0) - Only For Premium Account
				mode : "table", // "table", "ticker", "series"
				decimals: 2, // number o decimals for all values including decimals (prices, price changes, change%...)
				candleSticks : false, //show candle sticks if mode is Series
				coloredCandles : false, //colored bars: red and green for negative and positive candles
				premiumAccount: false // To change poolInterval, set this to true - Only For Premium Account
				}
		},

**Comment by lavolp3** [comment]
disabled needs to be a boolean, not string 
```disabled: false```

Setting a string makes it true

**Comment by requiemmg** [comment]
Thank you, that fixed it. But if it was true, the module should not load at all. Here, the module was loaded but no data was pulled...anyway, thanks for your help!
