### ISSUE TITLE
Invalid API call

### ISSUE THREAD

**Issue by thymon13** [lavolp3/MMM-AVStock#20]
Hello,

Since a few days. I have an error log :

` [ERROR]  [AVSTOCK] Error: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY. `

Thx in advance

**Comment by lavolp3** [comment]
can you post your config or at least the tickers you are calling?
It seems that more and more tickers are being removed from alphavantage.

**Comment by thymon13** [comment]
Hello,

I calling : 

```
 name: "CAC40", 
symbol: "^FCHI",
```

**Comment by lavolp3** [comment]
You could try "C40.PAR" which is an ETF following the CAC40 index.
I can confirm "^FCHI" does not work (anymore) 
So the problem is Aplhavantage, not this module

**Comment by thymon13** [comment]
@lavolp3 
Hello 

C40.PAR does not work too

Same API CALL error with it

**Comment by lavolp3** [comment]
For C40.PAR only the Global Quote Call works.
So no chart unfortunately.

**Comment by thymon13** [comment]
Oh.. Damn

Thx for this information.
