### ISSUE TITLE
Nothing being displayed in Table

### ISSUE THREAD

**Issue by SavarA506** [lavolp3/MMM-AVStock#22]
Hey,
So I changed the last company to “amzn” but it still shows Samsung electronics and nothing shows in the table. Thanks

**Comment by lavolp3** [comment]
Have you restarted the mirror?
The changes are being fed into node_helper which calls the data. Node_helper.js does not change with a page refresh but with a restart of the server side of the mirror.

**Comment by SavarA506** [comment]
Hey,
I did restart the mirror after putting the code into the modules array in the config.js file. The config.js file is reading the code from the modules file as the table is shown and “Apple” “google” and “Samsung electronics” are shown along with the headings. Only the data is missing. Thanks.

**Comment by SavarA506** [comment]
Here is what it looks like:
![7DA45DA2-DE0D-4005-9E10-08C4D3B1C7AD](https://user-images.githubusercontent.com/67023834/85044176-466e5e80-b15b-11ea-8547-24c138dfc36f.jpeg)

**Comment by SavarA506** [comment]
Please help me with this matter.

**Comment by julianzur** [comment]
Could it be that the Alphavantage API has changed? I'm also seeing:

`[AVSTOCK] Error: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY.`

**Comment by lavolp3** [comment]
@julianzur no the aplphavantage API works. It seems to be getting limited more and more but AAPL and GOOG surely work.

**Comment by lavolp3** [comment]
@SavarA506 Sorry I don't have much time currently in the middle of holiday, job transition and other stuff.
I will take care of this asap while giving this module a bigger update.

Can you post your config entry in the meantime but please leave out the API key

**Comment by lavolp3** [comment]
The reason may be that I have pushed a breaking change for the table.
Have reverted the change on the master branch.
Please try again after a `git pull` and let me know if it works.
For now I'm working on the new changes in the dev branch.

**Comment by SavarA506** [comment]
What do I type in to CMD for a "git pull"

**Comment by lavolp3** [comment]
```
cd ~/MagicMirror/modules/MMM-AVStock  
git pull
```

**Comment by svlstriker** [comment]
But with your reverts my problem pops up again...
https://github.com/lavolp3/MMM-AVStock/issues/18

Something I have to change now?

**Comment by lavolp3** [comment]
@svlstriker thanks for letting me know. I'm working on a me version in the dev branch but will fix this issue in the master branch again tomorrow.

**Comment by lavolp3** [comment]
@julianzur @svlstriker @SavarA506 
I have pushed a big update to version 2.0.0.

Please update
```
git pull
npm install
```

Let me know if your issues are resolved.
Also, check out the new options. It should still work with the old ones.

**Comment by svlstriker** [comment]
looks good so far!
one more problem is with settings of width to any % value...
I had the issue, that without setting width, the chart overlaps only a few pixel another module...
so I wanted to set width to 95% but the result ist, that it decreases the size to round about 75%
But that is okay for me, nmot a real problem ;-)

BIG THANKS!

**Comment by lavolp3** [comment]
width is an issue for me since I wanted to implement a flexible design.
It may behave different in the next update.
Then it will be by default set to '100%'. You can then change it to any number you like.
Hopefully it works better that way, so stay tuned.

Will close this now since original issue has been solved
