### ISSUE TITLE
MMM-AVStock and french stocks

### ISSUE THREAD

**Issue by ghost** [lavolp3/MMM-AVStock#23]
Hello,
does this module work with euronext and french stocks and the CAC?

**Comment by lavolp3** [comment]
Try finding your stock in the stock search function of the Api
alphavantage.co/query?function=SYMBOL_SEARCH&keywords=CAC&apikey=NXXXXXXXXXXXXX

Just replace the keyword with anything you want to try out.
Weems to even work with the apikey above (which is obviously a fake one)

**Comment by lavolp3** [comment]
closed since this is an API issue, not a module issue. 
Let me know if you have trouble using above function
