### ISSUE TITLE
How to update the module?

### ISSUE THREAD

**Issue by ghost** [lavolp3/MMM-AVStock#24]
Hello. I wanted to update this module, is this correct?

```
cd MagicMirror/modules/AVStock
git pull
```

Thanks in advance

**Comment by lavolp3** [comment]
You need to move into the module folder.  The name is MMM-AVStock.

For a standard raspbian installation:
```
cd ~/MagicMirror/modules/MMM-AVStock
```
Then
```
git pull
```

**Comment by ghost** [comment]
```
Updating 4722947..2003da6
error: Your local changes to the following files would be overwritten by merge:
	package-lock.json
Please commit your changes or stash them before you merge.
Aborting
```
this is what I get when I try to git pull. what's the best way to go about this?
thank you in advance

**Comment by lavolp3** [comment]
There are two ways. Use either one or both
1) delete package-lock.json
It is not necessary for the module to run. 
2) `git reset --hard`
This sets the status of the git repository to the latest published one and resets all local changes

**Comment by ghost** [comment]
it worked! thank you. i deleted the package-lock.json file.
