### ISSUE TITLE
Australian Stock issue

### ISSUE THREAD

**Issue by peterd550** [lavolp3/MMM-AVStock#25]
Hi Guys,
I cant seem to get Australian stock on the module for my magic mirror

Im trying to get anz for example and in my config.js I have tried

ANZ
ANZ.AX
anz
anz.sx

But still does not deplay

Google works well

Any ideas?

		{
  			//disabled:true,
  			module: "MMM-AVStock",
 			 position: "top_right",
			 config: {
    					apiKey : "MY-API-KEY",
    					symbols : ["aapl", "anz", "nab", "iag", "bhp", "s32"],
 				 }
		},

**Comment by lavolp3** [comment]
This is an API issue and they seem to have dropped support for Australian stocks.
https://www.reddit.com/r/ausstocks/comments/f3illc/alphavantage_for_asx/fsiosth/
THere's nothing that can be done in this module except another API source.

**Comment by lavolp3** [comment]
Try finding your stock in the stock search function of the Api
https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=Austsino&apikey=NXXXXXXXXXXXXX

Just replace the keyword with anything you want to try out.
Weems to even work with the apikey above (which is obviously a fake one)
