### ISSUE TITLE
Stocks not updating after latest update

### ISSUE THREAD

**Issue by kevmang** [lavolp3/MMM-AVStock#28]
Hi There

Stocks don't seem to be working with the latest update (2.0). Config included below. Have there been any changes to any of the config attributes?

		{
			"module": "MMM-AVStock",
			"header": "US Stocks",
			"position": "top_right",
			"config": {
				"apiKey": "mykey",
				"timeFormat": "DD-MM-YYYY",
				"symbols": [
					"VOO",
					"QQQ",
					"AAPL",
					"MSFT",
					"AMZN",
					"GOOGL"
				],
				"alias": [
					"S&P 500 ETF",
					"NDQ 100 ETF",
					"Apple Inc",
					"Microsoft Corp",
					"Amazon.com Inc",
					"Alphabet Inc"
				],
				"tickerDuration": 900,
				"chartDays": null,
				"mode": "table",
				"decimals": 4
			}
		},

**Comment by lavolp3** [comment]
Have you done 
```
npm install
```
after the update? 
That's necessary.
Also restart your mirror via pm2 or however it is running.

**Comment by kevmang** [comment]
Thanks for your reply, yes I've tried this but the tickers are appearing as "--".

I've made a Google Sheets workaround (with the Google Sheets Module) for the time being and will try again next update.

**Comment by lavolp3** [comment]
Your config entry has quotes around every key as if it was json format. That's not intended. Not sure if that's the problem however.
Please try the sample config from the readme and start from that.
Also note that it may take a few minutes for the first values to appear.

**Comment by koles0ff** [comment]
Hello,

Having same issue for ~3 month already. Please advise, how can I check module logs? 
Module updated, api key checked. Havo no idea what to check more. Config is very simple:

module: "MMM-AVStock",
  position: "bottom_center",
  config: {
        apiKey : "mykey",
        symbols : ["EURRUB=x","RUB=x"],
        alias: ["EURO","USD"],
        timeFormat: "YYYY-MM-DD HH:mm:ss",
        }

**Comment by lavolp3** [comment]
@koles0ff

`symbols : ["EURRUB=x","RUB=x"]`

These symbols cannot be interpreted.
Try
`symbols : ["EURRUB","USDRUB"]`

You can check module logs by including 
`debug: true`

**Comment by koles0ff** [comment]
This was quite lame from my end... Thanks! I wonder how this worked with this config :D 
It is working now.

**Comment by lavolp3** [comment]
Great!
Your module worked before but the API returned an empty list (not an error) and therefore nothing was sent to the front-end

**Comment by kevmang** [comment]
> b

Unfortunately no luck @lavolp3. I've verified my Alphavantage API (was the same before update anyway, but doesn't hurt to double check!). I've also cleared my old config and tried your sample config - replacing the API key with my own of course. Very strange!

**Comment by kevmang** [comment]
@lavolp3 figured out the issue after going back to your default config and adding everything one by one... it was the chartDays: null, command! Love the new grid mode by the way, thanks for all your efforts bringing this to the community.

**Comment by lavolp3** [comment]
@kevmang good catch. Dont find this anywhere in the readme or main js. It's always `chartDays: 90`.
If there is something that you think should be changed let me know.
