### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by ezar** [lavolp3/MMM-AVStock#30]
Hi @lavolp3 and thanks for the current update, very nice.

Can you change font size? I add #AVSTOCK * to my custom.css but it might be interesting to be able to configure medium, large, small.

**Comment by lavolp3** [comment]
I have done this already in the dev branch.
There will be a 'class' option responding with the usual font sizes integrated in main.css

**Comment by ezar** [comment]
Thanks!

**Comment by lavolp3** [comment]
New merge V 2.1.0 should include this option now. Look into the readme.
