### ISSUE TITLE
Wrong stocks showing

### ISSUE THREAD

**Issue by hermannw** [lavolp3/MMM-AVStock#32]
I installed this module today and copied the "Simple" configuration. Apple, Google and Tesla showing up. Great. Now let's see some other stocks. So I change:
`symbols : ["AAPL", "GOOGL", "TSLA"],`
to 
`symbols : ["MSFT", "AMZN"],`
Nope. Still showing Apple and Google. But it only shows two, So it got the number right but not the code. No matter what I enter in symbols, it only shows Apple, Google and Tesla. I even changed the js file and left the symbols out in the config but still the same.
Am I doing something wrong here?

Hermann

**Comment by SteTR** [comment]
Am also having the issue when setting different stocks.

**Comment by lavolp3** [comment]
You are only seeing the current aliases.
Set the option `alias: []` or fill the array with aliases. I will set the array as default empty with the next update.

**Comment by lavolp3** [comment]
V2.1.0 now sets alias: [] by default so you only see the symbol name.
Let me know if your problems still exist

**Comment by hermannw** [comment]
Vielen Dank  Dirk!
It works now and I like the "grid" view. But it seems "stuck" in that view. mode: "table" does not change it and ticker still shows the chart on half of the left side.

Hermann

**Comment by lavolp3** [comment]
@hermannw that seems impossible. Are you sure? The mode determines the DOM elements that are created. I wouldn't know how that would not change with a different entry. Of course restarting the mirror helps.
