### ISSUE TITLE
"Direction" doesn't seem to work

### ISSUE THREAD

**Issue by hermannw** [lavolp3/MMM-AVStock#38]
Hi guys, thanks for the work you are putting into this!
I like the possibility to show the purchase price. Would it be possible to show that in the table and grid view too?
The "direction" doesn't seem to do anything. It doesn't matter if I select row or column in table / grid, the stocks always show at the top and the chart below. Is there anything else I have to set to show them side by side like in your screen shot? And yes, I have restarted MMM after changing the config :-)

Edit: Looking at the source code, I notice that you are setting "width" to 100% and not 400px as you say in the configuration options. Setting width to e.g. 500 in the configuration file. placed the stocks and chart side by side.

Hermann

**Comment by lavolp3** [comment]
Thanks Hermann

For the first point: I'm planning that. 
For the second point. 
Showing the parts in one row only works when 'width' is half of the space that the module had in the specific region. 
So if you have a vertical view mirror (1000px width) and show the module in top or bottom bar you could try setting 'width' time a value below 500.
If you don't set width it is automatically 100%, so each part had a width of 100%.

You may see that I'm still developing this

**Comment by hermannw** [comment]
Thanks Dirk, I noticed that we were typing at the same time...

**Comment by lavolp3** [comment]
fixed with latest merge

**Comment by hermannw** [comment]
Looks great!
