### ISSUE TITLE
display bug since the last update (2 september 2020)

### ISSUE THREAD

**Issue by thymon13** [lavolp3/MMM-AVStock#41]
Hello !

First sorry for my english
I have an issue since few days

the display of the module is in plain middle

<a href="https://ibb.co/ZNf2JPd"><img src="https://i.ibb.co/521K9yT/IMG-3560.jpg" alt="IMG-3560" border="0" /></a>

```
{
  module: "MMM-AVStock",
  position: "top_left,
  config: {
    apiKey : "HIDEN :-) ",
    coloredCandles : true,
         symbols : ["C40.PAR"],
    alias: ["CAC40"],
        mode : "table",
        width: 400,
        decimals: 2,
        poolInterval : 5 * 60 * 1000,
        tickerDuration: 5, // Ticker will be cycled once per this second.
        timeFormat: "DD-MM-YYYY HH:mm:ss",
  }
},
```

**Comment by lavolp3** [comment]
> position: "top_left,

I assume the missing comma is present in your config?
It needs to be
```
  position: "top_left",
```

**Comment by lavolp3** [comment]
Another problem is that `width: 400` does not work for your table.
I don't have  soluton for that yet, but the table extends well beyond 400px when the class is `'small'` or bigger and when there are enough header fields.
You can remove the purchPrice headers (which you don't need in this specific case by setting in your config:
```        
        tableHeaders: ["symbol", "price", "close", "change", "changeP", "volume"],
        tableHeaderTitles: ["Symbol", "Price", "Close", "CHG", "CHG%", "Vol"],
```

**Comment by lavolp3** [comment]
OK we've found a solution.
For now please add
```
direction: 'column',
```
to your config.
With the next update I'll change the standard value.
Please confirm that it works

**Comment by thymon13** [comment]
@lavolp3 Yes it works !!

Thx a lot :)
