### ISSUE TITLE
disable Direction

### ISSUE THREAD

**Issue by thymon13** [lavolp3/MMM-AVStock#42]
Hi !

Is it possible to disable the direction display ?
And see only the graph

**Comment by lavolp3** [comment]
yeah the function has somehow been "lost" during the latest updates.
Try giving mode any other value, e.g. keep it empty 

```  
mode: "",
```

Let me know if it works. I can't test it right now.
If it doesn't work, try setting `mode: 'series'`

**Comment by thymon13** [comment]
nothing works... 

'series' or any other value. Empty too

**Comment by lavolp3** [comment]
Have you activated the chart? (should be by default)

```
showChart: true,
mode: '',
```

Or better, just post your config. :-)

I'll make it more clear in the README with the next update.

**Comment by thymon13** [comment]
```
{
  module: "MMM-AVStock",
  position: "top_right",
  config: {
    apiKey : "XXXXXXXXXXXXX",
    coloredCandles : true,
         symbols : ["C40.PAR"],
    alias: ["CAC40"],
        mode : "table",
        direction: 'column',
        classes: 'xsmall',
        showChart: true,
        showVolume: false,
        showPurchasePrices: false,
        showPerformance2Purchase: false,
        chartDays: 30,
        width: 350,
        decimals: 2,
        poolInterval : 5 * 60 * 1000,
        tickerDuration: 5, // Ticker will be cycled once per this second.
        timeFormat: "DD-MM-YYYY HH:mm:ss",
  }
},

```

**Comment by lavolp3** [comment]
using your config and only setting `mode: ''` works for me and shows only the graph
![image](https://user-images.githubusercontent.com/20084205/94965508-eded8200-04fb-11eb-9ef6-05ed55b5766f.png)

Does the module work with above config? You have set `mode:'table'` there

**Comment by Guandi303** [comment]
I think thymon13 meant that only the graph is showing and the blue boxes and the numbers on the right are gone

**Comment by lavolp3** [comment]
@thymon13 can you give an update? Still something not working?
Otherwise I'll close this.

**Comment by lavolp3** [comment]
> 
> 
> I think thymon13 meant that only the graph is showing and the blue boxes and the numbers on the right are gone

That's impossible with the latest update. Currently the blue boxes and numbers are hardcoded in JS.

**Comment by lavolp3** [comment]
@thymon13 if @Guandi303 guessed right and you wanted to have a pure graph, that's possible now with the latest update. Please update and have a look at the Readme.
