### ISSUE TITLE
Ticker view with several lines (without ticker)

### ISSUE THREAD

**Issue by spitzlbergerj** [lavolp3/MMM-AVStock#45]
Hello Dirk @lavolp3 ,
I use the ticker view, but not as a ticker (tickers are too restless for me), but as a fixed line display. I make this change via CSS.

But now I would like to display more stocks than fit into one line. I have integrated such a "newLine function" into my fork of the module MMM-NetworkScanner: see [here](https://github.com/spitzlbergerj/MMM-NetworkScanner/blob/master/MMM-NetworkScanner.js#L239).

Would this be interesting for your module? But I am afraid that I would destroy the ticker for those who want to use it. And I don't know enough about CSS to find a solution e.g. by using a parameter to switch off the ticker.

so I would probably need your help.

What do you think?

Regards
Josef

**Comment by lavolp3** [comment]
Hi Josef, 
have you checked out the "grid" mode?
We could amend it to show less information, so the grid elements are not bigger than a ticker element.

**Comment by lavolp3** [comment]
Josef any comment on this. Otherwise I'll close it

**Comment by spitzlbergerj** [comment]
Hi Dirk,
sorry, I have missed this hint. I will try this and get back to you if necessary. You are welcome to close the issue.
Please excuse me again.
Greetings
Sepp
