### ISSUE TITLE
Series gone

### ISSUE THREAD

**Issue by rodrigolousada** [lavolp3/MMM-AVStock#47]
Hi, I was using the 'series' mode to have a clean line showing me the variation of prices in the last days. Since I updated the module, I lost the line

**Comment by lavolp3** [comment]
can you post your config please?
Have you also run `npm install` after the update?

**Comment by rodrigolousada** [comment]
Thanks for the fast reply @lavolp3 
Yes, I ran the `npm install` after the update. My config looks like this:

```
{
	module: "MMM-AVStock",
	position: "top_right", //"bottom_bar" is better for `mode:ticker`
	config: {
		apiKey: credentials.AlphavantageApiKey, // https://www.alphavantage.co/
		timeFormat: "YYYY-MM-DD HH:mm:ss",
		symbols : ["ACN", "APPL", "VISA", "KO"],
		alias: ["Accenture", "Apple", "VISA", "Coca-Cola"], //Easy name of each symbol. When you use `alias`, the number of symbols and alias should be the same. If value is null or "", symbol string will be used by default.
		tickerDuration: 30, // Ticker will be cycled once per this second.
		chartDays: 10, //For `mode:series`, how much daily data will be taken. (max. 90)
		mode : "series", // "table", "ticker", "series"
		decimals: 4, // number o decimals for all values including decimals (prices, price changes, change%...)
		candleSticks : false, //show candle sticks if mode is Series
		coloredCandles : false, //colored bars: red and green for negative and positive candles
		premiumAccount: false, // To change poolInterval, set this to true - Only For Premium Account
	},
}
```

I tried to revert all the changes I made trying to fix. However, I can't assure you that everything is like before.

It was looking like this before the update:
![avstock](https://user-images.githubusercontent.com/24738828/100555756-9ff3c100-3295-11eb-810a-2b6dc83a8879.jpg)

Right now, it looks like this:
![image](https://user-images.githubusercontent.com/24738828/100555786-cf0a3280-3295-11eb-92bd-d35054bf2658.png)

**Comment by lavolp3** [comment]
Ah you mean it's not a simple line anymore but a graph.
Well I updated the module to this look.

You can exclude the volume bars by adding 
```
  showVolume: false
```

For the alteranting grid colors, I don't have a solution yet, that would have to be implemented.

**Comment by lavolp3** [comment]
not sure why your graph does not extend over the whole width. of the module.
I'll try out your config in my environment

**Comment by yoh33zy** [comment]
I used this code above because I really liked the view. The only issue is that I only ever get the 1st stock to show up... is there a way for it to show the other stocks too? Transitioning in and out in one position.

**Comment by rodrigolousada** [comment]
Thanks @lavolp3 ! It would be amazing to have this clean look back as an option (I noticed that "series" is not mentioned in the documentation anymore). I really liked it :)
Regarding the width, I noticed it only happens in some Symbols. Accenture shows this problem, but Coca-Cola doesn't

**Comment by lavolp3** [comment]
> 
> 
> Thanks @lavolp3 ! It would be amazing to have this clean look back as an option (I noticed that "series" is not mentioned in the documentation anymore). I really liked it :)
> Regarding the width, I noticed it only happens in some Symbols. Accenture shows this problem, but Coca-Cola doesn't

Thanks for the hint. Might be an issue when table/ticker/grid are deactivated. I have an idea for a cause.

`series` mode can still be chosen. I'll add it to the Readme again.

**Comment by lavolp3** [comment]
> 
> 
> Thanks @lavolp3 ! It would be amazing to have this clean look back as an option (I noticed that "series" is not mentioned in the documentation anymore). I really liked it :)
> Regarding the width, I noticed it only happens in some Symbols. Accenture shows this problem, but Coca-Cola doesn't

@rodrigolousada 
New option `pureLine` now added. Please check the Readme and try it out.

**Comment by lavolp3** [comment]
Closing this for now. Please reopen if you still have the issue

**Comment by rodrigolousada** [comment]
I am sorry for the late reply. I checked the README, however I may be doing something wrong:
```
{
    module: "MMM-AVStock",
    position: "top_right", //"bottom_bar" is better for `mode:ticker`
    config: {
    apiKey :credentials.AlphavantageApiKey, // https://www.alphavantage.co/
    timeFormat: "YYYY-MM-DD HH:mm:ss",
    width: "20",
    symbols : ["ACN", "APPL", "VISA", "KO", "MSFT", "SPWR"],
    alias: ["Accenture", "Apple", "VISA", "Coca-Cola", "Microsoft", "SunPower Corp"], //Easy name of each symbol. When you use `alias`, the number of symbols and alias should be the same. If value is null or "", symbol string will be used by default.
    tickerDuration: 20, // Ticker will be cycled once per this second.
    chartDays: 90, //For `mode:series`, how much daily data will be taken. (max. 90)
    mode : "series", // "table", "ticker", "series"
    pureLine: true,
    showVolume: false,
    chartInterval: "daily",
    decimals: 4, // number o decimals for all values including decimals (prices, price changes, change%...)
    chartType: 'line',                // 'line', 'candlestick', or 'ohlc'
    coloredCandles : false, //colored bars: red and green for negative and positive candles
  },
```

![image](https://user-images.githubusercontent.com/24738828/105108167-97f41880-5ab1-11eb-8b36-9a572df43c3e.png)

**Comment by lavolp3** [comment]
you set `width: '20'`.

Try setting that to an integer value (that's bigger than 20), e.g. `with: 400` or deleting it to automatically set it to 100%.

**Comment by rodrigolousada** [comment]
Yes, it was it! Thank you so much :)

Also, just found out that the graph does not extend over the whole width only on the generation. After switching the graph the first time, it works fine :)
