### ISSUE TITLE
Chart only shows a little until a symbol gets clocked on or ticks

### ISSUE THREAD

**Issue by ghost** [lavolp3/MMM-AVStock#49]
its in the upper_third section with

.MMM-AVStock {
padding-top: 450px;
transform: scale(0.7);
}

in custom.css

this is my config

			{			
			module: "MMM-AVStock",
			position: "upper_third",
			config: {
				apiKey : "XX9PEJ95PODWY2CX",
				timeFormat: "DD-MM HH:mm",
				width: null,
				symbols : ["AAPL", "GOOGL", "AMZN", "GP", "SHLX", "AMD", "TSLA", "OMP", "DHT", "GECC", "CCL", "MO", "DGRO", "DGRW", "LOW", "CVS"],
				alias: ["APPLE", "GOOGLE", "AMAZON", "GPWR", "SHELL", "AMD", "TESLA", "OASIS", "DHT", "GECC", "CARNIVAL", "ALTRIA", "DGRO", "DGRW", "LOWES", "CVS"],
				purchasePrice: [120.45, 1234.56, 3002.34],
				tickerDuration: 20,
				chartDays: 90,
				maxTableRows: null,
				mode : "table", 				// "table" or "ticker" or "grid"              
				showChart: true,
				showPurchasePrices: true,
				showPerformance2Purchase: true,
				chartWidth: null,
				showVolume: true,
				chartInterval: "daily",          // choose from ["intraday", "daily", "weekly", "monthly"]
				movingAverage: {
					type: 'SMA',
					periods: [200]
				},
				decimals : 2,
				chartType: 'candlestick',                // 'line', 'candlestick', or 'ohlc'
				chartLineColor: '#eee',
				chartLabelColor: '#eee',
				coloredCandles: true,
				debug: false
			  }
		},

would like it to load the whole chart on startup, bug

**Comment by lavolp3** [comment]
I can't really imagine the look of your issue. Can you post a picture?
Also, why do you have 
```
padding-top: 450px;
```
in custom.css? What do you need that for?

**Comment by ghost** [comment]
thats because the app was going above my top_bar which was a newsfeedticker,

and ill post a picture of it when i can, i started using smartwebdisplay and spreadsheets instead but im going to try giving your app another run after the new year, just trying to get this finished for a present for someone, but yeah basically when the app loads on the carousel its almost fullscreen with 2 columns on each side and when it switches to its window the chart will only load half the length of the rest of the application (half the window horizontally) under the tickers for the stocks until a ticker gets updated then the full chart will pop out under it

**Comment by lavolp3** [comment]
I think I understnd your issue now, have also created a similar one #53 .
WIll have a look at it.

**Comment by Nickred896** [comment]
Having the same issue. table only shows info for one ticker at a time until the chart updates to show the next ticker, then it shows the info for the next stock too, repeat until the chart has cycled through all stocks and all stocks are showing on the table. It also seems to be showing outdated prices (yesterday's close) until the 2nd time around on the chart updates.

**Comment by lavolp3** [comment]
Has been resolved in the meantime
