### ISSUE TITLE
Feature suggestion: Automatic currency conversion

### ISSUE THREAD

**Issue by requiemmg** [lavolp3/MMM-AVStock#51]
Hi,

I am using the IEXCloud version. Quite nice.
Would it be possible to add a per-stock currency conversion? I get most prices in US$ while my bank shows everything in EUR.
Automatically get US$-EUR. And also apply to purchase prices.

**Comment by lavolp3** [comment]
Good idea, but I think it might be irritating because if you show the value in EUR it looks like it lists a European exchange while the real price in European exchanges is different.

I'm thinking about it.

**Comment by lavolp3** [comment]
New API yahoo finance also supports foreign tickers.
So it makes more sense to use a European exchange if you want EUR prices instead of converting the US stock price.
Closing this for now
