### ISSUE TITLE
Positioning of the Graph and Table - mode:table 

### ISSUE THREAD

**Issue by Martin2K02** [lavolp3/MMM-AVStock#59]
How do I configure it just like that picture, that the table is above the graph? Because with "mode: table", the table is on the left side of the graph.

This is what I want:
![avstock-table](https://user-images.githubusercontent.com/42065778/118509115-12673900-b730-11eb-9c43-5d08b29a4ab0.png)

This is what I have now:
![image](https://user-images.githubusercontent.com/42065778/118509377-43476e00-b730-11eb-939b-b30b26266382.png)

**Comment by lavolp3** [comment]
Try the config option
```
direction: 'column',
```

If that doesn't help you could try giving the module a fixed width in custom.css

```
#AVSTOCK {
  width: 500px
}
```

**Comment by Martin2K02** [comment]
Thank You. Now It's in a position, that I wanted to have.
![image](https://user-images.githubusercontent.com/42065778/118621555-c3201780-b7c6-11eb-9e2c-1016e00e1d54.png)

But I have a question. Is it normal, that the value from the share is not exactly correct? Because officially right now It's on 2636,44 GBP and on the module It's 2612 GBP. When does it refresh the value?

**Comment by lavolp3** [comment]
The reason is the API that is being used. Alphavantage currently only drops last days closing values and does not update for the day. I am working on using yahoofinance and close to publishing. 
For months now ..... And maybe forever....

**Comment by Martin2K02** [comment]
Ok, I understand. Thank You.

Dann wünsche ich dir Viel Glück und hoffe dass es bald klappen wird und nochmals Danke für deine Hilfe.
