### ISSUE TITLE
Width only effects graph, not the stock headline

### ISSUE THREAD

**Issue by sowhat621** [lavolp3/MMM-AVStock#60]
I've tried many stuff, to get the hole thing a little bit smaller - but the only ones I could change was the graph.

![2021-11-26 00_00_37-Window](https://user-images.githubusercontent.com/57908681/143506592-63cc4072-fda6-43ed-80e8-90c45ae383aa.jpg) with no width setting or adjusting the *.css file Its bigger than the rest on the left and cuts It

![2021-11-25 23_59_43-Window](https://user-images.githubusercontent.com/57908681/143506623-01426b52-78e6-463d-85c5-b7c5c0e5236f.jpg)
but If u set the width in the Mirror Config File to width: '75',, It only cuts the graph, but not the headline with the stock (75 just for testing)

**Comment by lavolp3** [comment]
That's right, and intended. The stock  table is a table and cannot be made smaller since the contents would not fit anymore.
You can try to set a grid or a ticker as view mode (config option: `mode: 'grid'` or `mode: 'ticker'`), these are more adaptable.
