### ISSUE TITLE
API Broken?

### ISSUE THREAD

**Issue by Dresch360** [lavolp3/MMM-AVStock#62]
Looks like the stocks are no longer displaying. Wondering if AlphaVantage revised their API?

**Comment by hermannw** [comment]
I noticed that too...

**Comment by bclinton1** [comment]
Same here....

**Comment by gnurph69** [comment]
AlphaVantage now saying this is a premium API call.

**Comment by bclinton1** [comment]
Thanks for the info. Time to look for something else I suppose :)

**Comment by SleipnirMS** [comment]
When using chartInterval = daily, you have to set it to "daily_adjusted" and replace both "daily" entries in node_helper.js to "daily_adjusted".

Then it uses the free api part and everything is fine again.

**Comment by hermannw** [comment]
It works indeed! Thank you very much!

**Comment by bclinton1** [comment]
> When using chartInterval = daily, you have to set it to "daily_adjusted" and replace both "daily" entries in node_helper.js to "daily_adjusted".
> 
> Then it uses the free api part and everything is fine again.

Awesome. Thanks for sharing this.

**Comment by Dresch360** [comment]
Thank you so much! This worked.

**Comment by lavolp3** [comment]
I don't really know why but it works for me with the "daily" function, but not with the "daily_adjusted" function.
So try to change it back or do a git reset.

The error only seemed to appear for me when calling technical parameters (in my case SMA20) with the call. So, daily_adjusted with technical parameters seems to be a premium function. "Daily" calls seem to work
