### ISSUE TITLE
access multiple stock exchanges

### ISSUE THREAD

**Issue by TimoFrancke-cnic** [lavolp3/MMM-AVStock#68]
Is there a format to access stock prices from other stock exchanges? Toronto, London, etc. 

If there is, I think it should be added to the Readme.

**Comment by lavolp3** [comment]
I haven't tried. Can you provide me with a few example tickers?

**Comment by TimoFrancke-cnic** [comment]
I discovered Yahoo accepts it by submitting a letter for the stock exchange at the end, eg THG.L. 
it looks like Alpha uses a different format for their stocks. "LSX:THG" might be required.

**Comment by lavolp3** [comment]
"THG.L" works.
Note that I am not using Alphavantage anymore but yahoo finance.
So you could test out your ticker with yahoo finance and then include it in the config when it works.

**Comment by TimoFrancke-cnic** [comment]
I didn't know Alphavantage wasn't used at all, since the API key was still mentioned in the Readme. Thank you.
