### ISSUE TITLE
How do you adjust the timeframe on the chart?

### ISSUE THREAD

**Issue by thymon13** [lavolp3/MMM-AVStock#71]
Hello @lavolp3 

Thanks for your work !
I don't understand how to adjust the chart. As you can see below, the chart spans over 1 year, but the data is spread over 1 month.
![avstock](https://github.com/lavolp3/MMM-AVStock/assets/18228022/8fa3f23b-daa9-4de9-a26b-37d7a80b6c68)

`chartDays: 90,`

"What option should I modify? Because I've tried a bit of everything..." ?

thx in advance.

**Comment by lavolp3** [comment]
Hi thymon, can you post the complete config please?

**Comment by thymon13** [comment]
> Hi thymon, can you post the complete config please?

Yes sure 👍 

**{
  //disabled:true,
  module: "MMM-AVStock",
  position: "top_right",
  config: {
    apiKey : "hidden",
    coloredCandles : true,
         symbols : ["^FCHI","BTC-USD"],
    alias: ["CAC40","BitCoin"],
        mode : "table",
        direction: 'column',
        classes: 'xsmall',
        showChart: true,
        showVolume: false,
        showPurchasePrices: false,
        showPerformance2Purchase: false,
        chartType: 'line',
        coloredCandles: true,
        chartDays: 90,
        width: 350,
        decimals: 2,
        poolInterval : 5 * 60 * 1000,
        tickerDuration: 5, // Ticker will be cycled once per this second.
        timeFormat: "DD-MM-YYYY HH:mm:ss",
  }
},**

**Comment by andygodber** [comment]
Hi both - did this get resolved? I couldnt get the date range to change either.
I experimented with chartWidth - any value 449 or below seems to make the x-axis have correct labelling, but no content.
If its 450 or above, you get the data but x-axis tries to show a 1 year view. (but only c 60 days of content)
Also, the chartDays value seems to have no effect.

**Comment by rmcelwee** [comment]
> Hi both - did this get resolved? I couldnt get the date range to change either. I experimented with chartWidth - any value 449 or below seems to make the x-axis have correct labelling, but no content. If its 450 or above, you get the data but x-axis tries to show a 1 year view. (but only c 60 days of content) Also, the chartDays value seems to have no effect.

Just as a data point, I have the same problem as you with my single stock chart. I get a chart area that spans the width of my monitor but the line only takes a small percentage of it. It does move from time to time, I think at the begging of a new month. So, your line is at the far right of the chart and 30 days later it will move to the middle of the chart. I wouldn't mind if I could display two of them side by side (say a 1 year chart and a 1 day chart of the same stock) but I haven't found a way to do that.

**Comment by lavolp3** [comment]
can you please check again with the latest update and report back? @rmcelwee

**Comment by rmcelwee** [comment]
I did the following and the trendline is still "small":

rm -r node_modules

npm install

**Comment by lavolp3** [comment]
The `git pull` was probably missing.
For an update of a module you always need to do a git pull, then best to update the dependencies as well.

```
rm -r node_modules
rm package-lock.json
git pull
npm install
```

**Comment by lavolp3** [comment]
> Hi both - did this get resolved? I couldnt get the date range to change either. I experimented with chartWidth - any value 449 or below seems to make the x-axis have correct labelling, but no content. If its 450 or above, you get the data but x-axis tries to show a 1 year view. (but only c 60 days of content) Also, the chartDays value seems to have no effect.

@andygodber 
Not sure if it adresses your issue but I fixed an error in the chart yesterday. You're invited to try out as well.

`chartDays` option should work now again as well.

**Comment by rmcelwee** [comment]
Yes, that was it. The chart looks much better now. Thanks!

**Comment by lavolp3** [comment]
@andygodber @thymon13 can you let me know if the module works for you now as expected? Thanks!

**Comment by andygodber** [comment]
> @andygodber @thymon13 can you let me know if the module works for you now as expected? Thanks!

Looks good - thanks for fixing

**Comment by lavolp3** [comment]
thank you for the feedback. Closing this now.
