### ISSUE TITLE
All data stopped about 2 weeks ago?

### ISSUE THREAD

**Issue by rmcelwee** [lavolp3/MMM-AVStock#72]
All data stopped about 2 weeks ago (no stock chart or prices since then). Is anyone else seeing this? I restored a backup and the problem persists.

**Comment by lavolp3** [comment]
Yes, as I see now, Yahoo finance have stopped access to their quotes endpoint.
https://github.com/gadicc/node-yahoo-finance2/issues/764#issuecomment-2056623851

That is a killer for the module. 
I will follow that up but do not have a solution yet. 
I wanted to create a module with quotes AND history /chart data. I have looked for several different APIs but this was the easiest solution.

**Comment by lavolp3** [comment]
I pushed an update to the module, can you try it out please? @rmcelwee #
You need to do an `npm install` in the module folder.

**Comment by rmcelwee** [comment]
Sure thing. I just updated. I'll reboot and see if it comes up.

**Comment by rmcelwee** [comment]
Newbie, so let me know if I did it incorrectly. I went to the MMM-AVStock folder, typed sudo npm install and it said it was updating. I did a reboot and it did not work (no price data).

**Comment by lavolp3** [comment]
do the following
go into the module folder
type
```
rm -r node_modules
npm install
```
sudo should not be necessary

**Comment by lavolp3** [comment]
price data gets catched at my end, so it should work. 
![grafik](https://github.com/lavolp3/MMM-AVStock/assets/20084205/dfd7ae10-ef2b-47c4-957f-3049d24d5428)
The chart however does not look good, but i need to look at that some other time

**Comment by rmcelwee** [comment]
I did that and it updated. It does say "1 package is looking for funding"
after completion. After a reboot it still does not have price data.

**Comment by rmcelwee** [comment]
![Uploading 20240508_165626.jpg…]()

**Comment by rmcelwee** [comment]
![Uploading 20240508_165626.jpg…]()

**Comment by rmcelwee** [comment]
![Uploading 20240508_165626.jpg…]()

**Comment by lavolp3** [comment]
can't see your picture.

can you look for the file "package-lock.json" in the folder and then look for the entry "yahoo-finance2" and post its installed version?

**Comment by rmcelwee** [comment]
Sorry, not sure why the picture isn't posting. It was just a screenshot
showing that the chart data was not showing.
"yahoo-finance2": "^2.4.3"

**Comment by lavolp3** [comment]
> Sorry, not sure why the picture isn't posting. It was just a screenshot showing that the chart data was not showing. "yahoo-finance2": "^2.4.3"


OK that's the problem, you need the newest version of the yfinance module.
For some reason your system did not fetch the latest update to my module.


You should try what we may have missed, which is to delete the package-lock.json. This may "lock" the versions of the node modules:
From the module folder MagicMirror/modules/MMM-AVStock
```
rm -r node_modules
rm package-lock.json
git pull
npm install
```


If that doesn't work, probably the easiest way is to reinstall my module.

First go the MagicMirror/modules
```
rm -r MMM-AVStock
git clone https://github.com/lavolp3/MMM-AVStock
cd MMM-AVStock
npm install
```

**Comment by rmcelwee** [comment]
That's it! Works fine. I appreciate the command lines and the help. If you
get some spare time please look at "How do you adjust the timeframe on the
chart?". I only have two things on my mirror (monitor turned vertically).
MMM-CanlendarExt2 on the top 2/3rd of the screen and your AVStock on the
bottom 3rd. The chart background goes across the entire screen but the data
trendline only uses a small portion of that area. We only chart one stock.
Again, thank you for the great module and all the help!
