### ISSUE TITLE
Ticker Resets after 6 stocks

### ISSUE THREAD

**Issue by alicornea** [lavolp3/MMM-AVStock#75]
I have a ticker with 8 stocks but the last two cannot be seen as the position resets to 0.

**Comment by lavolp3** [comment]
Hi alicornea! 
I can't reproduce this. 8 stocks work for me. 
Could be a conflict with the width of the module.
Can you send me your config?

**Comment by lavolp3** [comment]
@alicornea anything? 
Otherwise I'll close it.

**Comment by alicornea** [comment]
it works now, thank you!
    On Wednesday, August 7, 2024 at 01:36:22 PM GMT+3, Dirk ***@***.***> wrote:  
 
 


@alicornea anything?
Otherwise I'll close it.
