### ISSUE TITLE
3 small things.

### ISSUE THREAD

**Issue by sanestsage** [lavolp3/MMM-AVStock#79]
The detailed example has "locale: config.language," which crashes the mirror. just set it to undefined?

BTC ticker returns the Greyscale btc ETF ticker at 5$ a pop.
the documentation listing_status.csv
[https://www.alphavantage.co/query?function=LISTING_STATUS&apikey=demo](url)
does not have the BTC ticker. I found a digital_currency_list.csv tho which has it. but with the same ticker and that obv doesnt work out. Im not rly into crypto so w/e but others might be interested?

In MMM-AVStock.js  line 641 is  alternateGridColor: '#223344', maybe make it changeable from the settings to #000. 
I really dont like a blue block of background on a mirror thats 95% black. Maybe i just overlooked this setting tho. idk.

It's a really great module tho! Exactly what i looked for. Really appreciate all the effort u put into this.

**Comment by lavolp3** [comment]
Thanks @sanestsage for the remarks. Will try to implement the changes soon!

**Comment by lavolp3** [comment]
BTW we are not using alphavantage anymore. The module is purely based on yahoo finance in the meantime. Can't change the name anymore 🤷

**Comment by lavolp3** [comment]
Have pushed your proposals and added alternateGridColor as option.
Try it out!
Reg BTC you could try adding 'BTC-USD' to your stocks.
