### ISSUE TITLE
MMM-Hello-Lucy

### ISSUE THREAD

**Issue by bazil1000** [lavolp3/MMM-AVStock#8]
Dear all,
Wondering if anyone has been successful in using Hello Lucy to hide/show this module. I've got it working or all other (non default) modules but this one doesn't seem to respond at all. I've also tried different command words Stock, Money, Stock Report and Shares. Non of these worked.

Any ideas? Much apprecited

**Comment by eouia** [comment]
Sorry, I'm not using Hello Lucy so I have no idea about it.

**Comment by bazil1000** [comment]
Are you able to review (or better still test) the instructions provided and comment on whether this approach works with AVStock. I suspect it may be the recommended location of the hide commands or the hide commands themselves that are not working for AVStock..?

Any help would be much appreciated!

**Comment by eouia** [comment]
I have no will to install or inspect HelloLucy just for test. Instead, I tried usual common methods to show/hide. And there seems no suspicious point in module itself. I think you'd better to ask to creator of HelloLucy.

**Comment by bazil1000** [comment]
Okay. Have you used any voice controls yourself? 

Also, have you given any thought to how you might, bring up trends on command rather than relying on a static either or approach?

**Comment by eouia** [comment]
I'm using MMM-Hotword & MMM-AssistantMk2. 
And I cannot understand your words; What does it mean? 
> Also, have you given any thought to how you might, bring up trends on command rather than relying on a static either or approach?
