### ISSUE TITLE
Currency conversion 

### ISSUE THREAD

**Issue by drystanm** [lavolp3/MMM-AVStock#9]
Is it possible to convert the stock price from USD into some other currency ? 
I have a stock that I want to monitor in CAD
Thanks

**Comment by eouia** [comment]
Interesting, but seems not so easy.
As far as I know, 
1) There is no base currency for whole API result. "APPLE(aapl)" has its stock price as USD, but "SAMSUNG Korea(005930.KS)" has its as KRW.  I don't know about Canadian business, but if there be companies which be registered on Canadian Stock market, it will be displayed as CAD.
2) Not so easy to detect which country market the company locates. It needs additional API request, or manually being set.
3) No currency conversion rate API is included. Additional 3rd party API for currency converter should be needed.
